export const PATH = {
  MAIN: '/',
  LOCKER: '/locker',
  LOGIN: '/login',
  NOTICE: '/notice',
  NOTICE_CREATE: '/notice/create',
  NOTICE_DETAIL: '/notice/:noticeId',
  NOTICE_EDIT: '/notice/edit/:noticeId',
  APPLY: '/locker/apply',
  SHARE: '/locker/share',
  SORT: '/sort',
  ASSIGN: '/assign',
  USER_SHARE: '/user/share',
  PROFILE: '/profile',
  CRITERIA: '/admin/criteria',
};
