name: Build and Deploy Preview

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Dependencies
        run: yarn install

      - name: Build Preview
        run: yarn preview

      - name: Deploy Preview
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: preview
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }}
