name: Create Preview Site
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  pages: write
  deployments: write

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: yarn install && yarn build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          if: contains(['opened', 'reopened', 'synchronize'], github.event.action)
          source-dir: ./dist/
          action: deploy
          preview-branch: gh-pages
          umbrella-dir: pr-preview

      - name: Remove preview
        uses: rossjrw/pr-preview-action@v1
        if: github.event.action == "closed" && !github.event.pull_request.merged
        with:
          source-dir: ./dist/
          action: remove
